export const CITY_NAME_ERROR = "City is not found!";
export const NOT_FOUND_CODE = 404;
export const BAD_REQUEST_CODE = 400;
export const SUCCESS_CODE = 200;
export const SERVER_ERROR_CODE = 500;
export const BASE_URL = "https://api.openweathermap.org/data/2.5/";
export const WEATHER_PARAM = "weather?q=";
export const API_KEY_PARAM = "&appid=";
export const PORT = 3000;
export const ERROR_PAGE = "Error Page";
export const APPLICATION_NAME = "Weather App";
